"""Add is_premium column to user_profiles

Revision ID: 629e718706b5
Revises: f8b36df0b9b9
Create Date: 2025-09-28 22:01:42.189099

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "629e718706b5"
down_revision: Union[str, Sequence[str], None] = "f8b36df0b9b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profiles",
        sa.Column(
            "is_premium", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profiles", "is_premium")
    # ### end Alembic commands ###
